name: Python CI (lint only)

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tools
        run: pip install -r requirements.txt
      - name: Check formatting
        run: |
          black --check .
          isort --check-only .
